### ISSUE TITLE
Using font awsome classes inside any other tag than "<i></i>" tag

### ISSUE THREAD

**Issue by patriciachrysy** [nyatindopatrick/Youtube-clone#2]
You should use the fa classes only inside icons tags, that's the best practice.

**Comment by Kyle-Law** [comment]
- In your terminal, `touch .gitignore` and put `.DS_Store` inside to ignore the unnecessary file; `rm .DS_Store` to remove the file; `ls -a` to see hidden files inside the directory.
- delete frameborder property
